---
apiVersion: v1
kind: Service
metadata:
  name: otcalculate-service
spec:
  selector:
    app: otcalculate-pod
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
  # externalIPs:
  # - 194.233.73.42

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otcalculate-deployment
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: otcalculate-pod
  template:
    metadata:
      labels:
        app: otcalculate-pod
      namespace: default
    spec:
      containers:
      - name: otcalculate-container
        image: otcalculate:tagVersion
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "1024Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
          protocol: TCP
      terminationGracePeriodSeconds: 0

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: otcalculate-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ot.msshifu.com
    http:
      paths:
      - backend:
          serviceName: otcalculate-service
          servicePort: 80